# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/llava',
                'doc_host': 'https://numb3r33.github.io',
                'git_url': 'https://github.com/numb3r33/llava',
                'lib_path': 'llava'},
  'syms': {'llava.core': {'llava.core.foo': ('core.html#foo', 'llava/core.py')}}}
