
    project_name: Adaptive_Patching_VIT_fastai
    paths:
      data_base: /path/to/datasets
      output_dir: /path/to/outputs
    model:
      llm_name_or_path: lmsys/vicuna-7b-v1.5
      vision_encoder_name_or_path: openai/clip-vit-large-patch14-336
    logging:
      wandb:
        enabled: true
        project: adaptive_patching_vit_test
        entity: your_wandb_entity # Replace with your entity
    